# Generated by Django 4.2.11 on 2024-04-08 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import store.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', django_resized.forms.ResizedImageField(crop=None, default='no_image.jpeg', force_format=None, keep_meta=True, quality=100, scale=None, size=[200, 200], upload_to=store.utils.get_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'user'], name='store_inter_product_ee5788_idx')],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
