# Generated by Django 5.0.3 on 2024-04-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_rating_product_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='star_rating',
            field=models.FloatField(default=0),
        ),
    ]
