# Generated by Django 4.2.11 on 2024-04-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0004_category_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='store.category'),
        ),
    ]
